danger.import_dangerfile(
  github: 'technekes/danger',
  path: 'Dangerfile'
)

# -----------------------------------------------------------------------------
# warn if github PR body length less than 5
# -----------------------------------------------------------------------------
if github.pr_body.length < 5
  warn 'Please provide a summary in the Pull Request description'
end

# -----------------------------------------------------------------------------
# Make it more obvious that a PR is a work in progress and shouldn't be merged
# -----------------------------------------------------------------------------
if declared_wip?
  fail('PR is classed as "wip" use GitHub native "draft" feature instead')
end

# -----------------------------------------------------------------------------
# Warn when there is a big PR
# -----------------------------------------------------------------------------
warn('Big PR') if git.lines_of_code > 500

# -----------------------------------------------------------------------------
# Don't let testing shortcuts get into master by accident
# -----------------------------------------------------------------------------
if `grep -r " xcontext" spec | grep -v spec_helper`.length > 1
  warn 'xcontext left in tests'
end
if `grep -r " xit" spec | grep -v spec_helper`.length > 1
  warn 'xit left in tests'
end
if `grep -r ":focus" spec | grep -v spec_helper`.length > 1
  fail ':focus left in tests'
end

fail('Please add a description for your PR') if github.pr_body.empty?

if github.pr_title.include?('build: bump incent from') || github.pr_title.include?('build: bump incent-config from')
  fail('Use `feat` instead of `build` for incent and incent-config version bumps')
end