danger.import_dangerfile(
  github: 'technekes/danger',
  path: 'Dangerfile'
)

fail('Please add a description for your PR') if github.pr_body.empty?

# ------------------------------------------------------------------------------
# Requre a CHANGELOG entry for library changes
# ------------------------------------------------------------------------------
if !changelog_modified? && app_changes? && !declared_trivial?
  changelog_message = <<-MESSAGE
    Please include a CHANGELOG entry. You can find it at ./CHANGELOG.md
  MESSAGE

  fail(strip_doc(changelog_message))
end
