danger.import_dangerfile(
  github: 'technekes/danger',
  path: 'Dangerfile'
)

fail('Please add a description for your PR') if github.pr_body.empty?

# ------------------------------------------------------------------------------
# Fail when PR body does not have ADO ticket number
# ------------------------------------------------------------------------------
fail('PR has no ADO ticket number') if !pr_has_ticket_number? && !release_branch?

# ------------------------------------------------------------------------------
# Warn when there is a big PR
# ------------------------------------------------------------------------------
warn('Big PR') if git.lines_of_code > 500
